#define configCPU_CLOCK_HZ       (16000000UL)
#define configTICK_RATE_HZ       (1000)
#define configMAX_PRIORITIES     (5)
#define configMINIMAL_STACK_SIZE (128)
#define configTOTAL_HEAP_SIZE    (10240)
#define configUSE_PREEMPTION     1
#define configUSE_16_BIT_TICKS   0
#define configUSE_IDLE_HOOK      0
#define configUSE_TICK_HOOK      0